### ISSUE TITLE
There is no method setEndorsingOrganizations() in  package org.hyperledger.fabric.gateway.Transaction，but method setEndorsingOrganizations() exits in fabric-gateway-node

### ISSUE THREAD

**Issue by songyingxian** [hyperledger/fabric-gateway-java#102]
Because of no method setEndorsingOrganizations() ， realizing application-java of asset-transfer-secured-agreement could not goes well.

**Comment by bestbeforetoday** [comment]
If you are using service discovery then in many cases it should pick the correct endorsing organisations. To make that work for chaincode-to-chaincode calls or private data collections, that really needs chaincode interests to be specified for the discovery query, which (unlike the Node SDK) the fabric-gateway-java API doesn't currently have a mechanism to do.

A workaround might be to explicitly specify the endorsing peers to use. You can find the peers for a given organisation with `network.getChannel().getPeersForOrganization(orgName)`. It's quite manual, so perhaps not ideal, but you should be able to get it to work. This is the same behaviour you would get when calling `setEndorsingOrganizations()` in the Node SDK if you are _not_ using service discovery.

If you are using Fabric v2.4 (or later), the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/) picks the correct endorsing organisations for nearly all scenarios, and has the option to set endorsing orgs for the small set where this is required.
