### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CarlLu** [hyperledger/fabric-gateway-java#107]
public static Properties parseGrpcUrl(String url) {
  Pattern p = Pattern.compile("([^:]+)[:]//([^:]+)[:]([0-9]+)", Pattern.CASE_INSENSITIVE);
}

The regularity here will directly lead to errors，Please modify

**Comment by bestbeforetoday** [comment]
Please could you provide more information on the specific failure scenario you see?

**Comment by bestbeforetoday** [comment]
@CarlLu can you provide any more information on what the problem is and what needs to change? Otherwise I'll close this as there isn't enough information to progress it.
