### ISSUE TITLE
Copy constructor of GatewayImpl doesn't copy HFClient configuration properly

### ISSUE THREAD

**Issue by Breina** [hyperledger/fabric-gateway-java#117]
Regarding https://github.com/hyperledger/fabric-gateway-java/blob/main/src/main/java/org/hyperledger/fabric/gateway/impl/GatewayImpl.java#L206

When copying the gateway, a new `HFClient` instance is created. The channel config and crypto suite are not copied over.

# Reproduction snippit

```java
        final var gateway1 = new GatewayImpl.Builder()
                .identity(identity)
                .networkConfig(networkConfigFile)
                .connect();
        HFClient client1 = gateway1.getClient();
        client1.setCryptoSuite(myCryptoSuite);
        client1.loadChannelFromConfig("channelName", myNetworkConfig);

        // Copy gateway
        final var gateway2 = gateway1.newInstance();
        final var client2 = gateway2.getClient();

        // We expect client2 to have the same configuration as client1
        Assertions.assertEquals(myCryptoSuite, client2.getCryptoSuite());
        Assertions.assertEquals(myNetworkConfig, client2.getChannel("channelName"));
```

# Context

The `GatewayImpl#newInstance` is called when `ReplayListenerSession` is constructed. Thus, whenever calling `Contract#addContractListener` (with an existing `Checkpointer`), the `HFClient` instance used will be the default one, which may not necessarily connect properly.

**Comment by bestbeforetoday** [comment]
I notice that your reproduction steps rely on using GatewayImpl directly rather than the Gateway interface. The `getClient()` method does not exist on the Gateway interface, and it is not really intended for use outside of the internals of the API implementation. Is this a real use-case or a theoretical bug in the API that only impacts use of "private" internals?

**Comment by Breina** [comment]
The bug at least is a real life bug that's causing us problems, the code was simply intended to demonstrate what's actually wrong. The code of a real life snippet is more complex and not easily separable.

In any case, the result is that the Gateway that ReplayListenerSession is using, does not have the proper SSL context.
