### ISSUE TITLE
unable to convert key pair: ECDSA KeyFactory not available

### ISSUE THREAD

**Issue by mlph-sreyes** [hyperledger/fabric-gateway-java#127]
Hi, 

I'm trying to implement fabric gateway as a part of a larger Java application. The application is written in **Java 17**, and I know that it is not yet supported according to the readme. I was hoping there is a minor workaround I can do only for the Identities part because the Java application is too big and requires a lot of refactoring just to revert it back to Java 11.

Specifically I am having problem with this part of the code:

var privateKey = `Identities.readPrivateKey(keyReader);`

This is the error that I am encountering right now:

![image](https://user-images.githubusercontent.com/72548707/204220726-4816f2e1-2564-4536-85d3-2450d5d24977.png)

![image](https://user-images.githubusercontent.com/72548707/204220796-de31c222-5aff-457b-a96c-0530abd07309.png)

Thank and I appreciate your time reading my concern.

**Comment by bestbeforetoday** [comment]
At some point testing with Java 17 was added but the README wasn't updated, so Java 17 is supported. There are unit tests of that code which run successfully with Java 17 - at least with PKCS#8 format private key PEM data.

- https://github.com/hyperledger/fabric-gateway-java/blob/00afa0c6a376feea492b9d9390ae9415b404289d/src/test/java/org/hyperledger/fabric/gateway/IdentitiesTest.java#L107-L113
- https://github.com/hyperledger/fabric-gateway-java/blob/00afa0c6a376feea492b9d9390ae9415b404289d/src/test/java/org/hyperledger/fabric/gateway/IdentitiesTest.java#L124-L131

Could it be that your private key is stored in a format not recognised by the BouncyCastle PEM reader?

Note that `Identities.readPrivateKey` is just a convenience method for reading a private key stored in PEM format to a **java.security.PrivateKey** object. If this isn't working for your case, you can use an alternative mechanism (standard Java library or a third-party library) to read the PEM and produce a **java.security.PrivateKey** object.

**Comment by mlph-sreyes** [comment]
Thanks for clarifying about my concern with the Java 17 support. I found a forum for Bouncycastle that tells me to add a specific BouncyCastleProvider using this code:

`Security.addProvider(new BouncyCastleProvider());`

I also declared a specific version(1.70 latest) of the bouncycastle dependencies in my pom.xml to avoid this error
`java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1Integer`

**pom.xml**
```
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.70</version>
</dependency>
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcmail-jdk15on</artifactId>
    <version>1.70</version>
</dependency>
```

**Comment by bestbeforetoday** [comment]
Interesting. When examining the fabric-gateway-java project locally, I already see that version of Bouncy Castle in my dependency tree:

```
[INFO] |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.70:compile
[INFO] |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.70:compile
[INFO] |  |  \- org.bouncycastle:bcutil-jdk15on:jar:1.70:compile
```

I wonder if your application is picking up a different Bouncy Castle version from another dependency and that is overriding the versions resolved in the fabric-gateway-java Maven dependency tree. By explicitly specifying a version in your project you would be preventing that from happening.

If you do manage to identify a simple scenario you can share that demonstrates a problem that can be fixed in the fabric-gateway-java code, please update this issue. Right now I am not able to reproduce the problem locally.
