### ISSUE TITLE
Use of complex data types while using submitTransaction of a contract

### ISSUE THREAD

**Issue by neosis** [hyperledger/fabric-gateway-java#83]
Hi,

Documentation of DataType annotation mentions that its used to annotate complex types that can be returned or passed to the transaction functions [Link](https://hyperledger.github.io/fabric-chaincode-java/release-2.2/api/org/hyperledger/fabric/contract/annotation/DataType.html) . Can we use these complex data types in submitTransaction of a contract? 

Best
Ashutosh

**Comment by bestbeforetoday** [comment]
The client API doesn't have any support for this annotation and doesn't provide any default serialisation implementation, but at the contract end there is some de/serialisation scheme based on the annotated types.

I suspect (but don't know for sure!) that the Contract will serialise the object to a JSON representation and return it as UTF-8 bytes. If that is the case, you can convert the returned `byte[]` to a `String` with `new String(result, StandardCharsets.UTF_8)`, then use your JSON parser of choice to parse the JSON object.

**Comment by mbwhite** [comment]
@bestbeforetoday  is correct here; I did think that this was documented, but appears I was wrong.

I shall need to correct this.
