### ISSUE TITLE
It takes time to close gateway

### ISSUE THREAD

**Issue by yoshiteru-imamura** [hyperledger/fabric-gateway-java#86]
There seems to be a 3 second wait on shutdown for managedchannel.
Therefore, the wait time increases with the number of peers.

Is there anything I can do to shorten the shutdown time?

Is it possible to select true as the argument for channel.shutdown in networkimpl.close?

Gateway.close->NetworkImpl.close->Channel.shutdown...PeerEventServiceClient.shutdown->lchannel.shutdown().awaitTermination(3,TimeUnit.SECONDS)

**Comment by bestbeforetoday** [comment]
Duplicates #87
