### ISSUE TITLE
org.hyperledger.fabric.gateway.ContractException: error in simulation: transaction returned with failure: Undefined contract called

### ISSUE THREAD

**Issue by Xingxingyeyouxinshi** [hyperledger/fabric-gateway-java#88]
I exported the connection profile  and wallet from IBP(IBM Blockchain Platform VSCode Extension) as my application configuration. 

when I used the fabric-gateway-java v2.2.0 reported this error when invoking the chaincode I developed in IBP:

`org.hyperledger.fabric.gateway.ContractException: error in simulation: transaction returned with failure: **Undefined contract called**
	at org.hyperledger.fabric.gateway.impl.query.SingleQueryHandler.evaluate(SingleQueryHandler.java:50)
	at org.hyperledger.fabric.gateway.impl.TransactionImpl.evaluate(TransactionImpl.java:220)
	at org.hyperledger.fabric.gateway.impl.ContractImpl.evaluateTransaction(ContractImpl.java:55)`

I'm pretty sure the called method is defined in the contract, and I can successfully call it in IBP.

anyone can help me fix it?

**Comment by bestbeforetoday** [comment]
This is an error message returned from the chaincode/contract runtime. It indicates that the contract name you specified does not exist within the chaincode package.

If you only have a single (default) contract within your chaincode, or you explicitly want the default contract, or you are using the lower-level shim API only (not the higher-level contract API), specify only the chaincode name when obtaining your Contract object, for example:

```java
Contract contract = network.getContract("chaincodeName");
```

If you have multiple named contracts in your chaincode, ensure you specify both the chaincode and contract name correctly, for example:

```java
Contract contract = network.getContract("chaincodeName", "contractName");
```

**Comment by Xingxingyeyouxinshi** [comment]
thanks, I have solved the problem.
