### ISSUE TITLE
Throw "commit strategy failed" when creating a transaction using fabric gateway?

### ISSUE THREAD

**Issue by 1164926307** [hyperledger/fabric-gateway-java#96]
Throw "commit strategy failed" when creating a transaction using fabric gateway.

However, the transaction has been submitted to the fabric network, which can be queried by using the "peer chain query" command at the terminal.

![a](https://user-images.githubusercontent.com/37772120/150674559-a38629e6-84fb-4369-9995-f4c70ba00dc8.png)
![b](https://user-images.githubusercontent.com/37772120/150674561-20579291-9154-4dbd-a94b-064f85a090f9.png)
![c](https://user-images.githubusercontent.com/37772120/150674563-590a74e5-e1ad-4b48-bb41-d09afefc28a2.png)

**Comment by bestbeforetoday** [comment]
The "Commit strategy failed" message indicates that the client timed out before receiving any block events containing the submitted transaction.

You are using the CLI to perform a query (read ledger state, which does not require events to be received), whereas you are using the SDK to submit a transaction (update ledger state). To perform a query you should be using [transaction.evaluate()](https://hyperledger.github.io/fabric-gateway-java/release-2.2/org/hyperledger/fabric/gateway/Transaction.html#evaluate(java.lang.String...)).

You do not need to set the endorsing peers unless you want to deliberately restrict the peers used for endorsement to a certain set. This might be when working with private data collections or state-based endorsement policies. Generally you should not set the endorsing peers.

**Comment by 1164926307** [comment]
> The "Commit strategy failed" message indicates that the client timed out before receiving any block events containing the submitted transaction.
> 
> You are using the CLI to perform a query (read ledger state, which does not require events to be received), whereas you are using the SDK to submit a transaction (update ledger state). To perform a query you should be using [transaction.evaluate()](https://hyperledger.github.io/fabric-gateway-java/release-2.2/org/hyperledger/fabric/gateway/Transaction.html#evaluate(java.lang.String...)).
> 
> You do not need to set the endorsing peers unless you want to deliberately restrict the peers used for endorsement to a certain set. This might be when working with private data collections or state-based endorsement policies. Generally you should not set the endorsing peers.

Thank you very much for your answer, which has solved my problem.

**Comment by bestbeforetoday** [comment]
👍
